export const dogBreeds = [
  "Affenpinscher",
  "Afghan Hound",
  "Airedale Terrier",
  "Akita",
  "Alaskan Malamute",
  "Alpine Dachsbracke",
  "American Cocker Spaniel",
  "American Staffordshire Terrier",
  "American Foxhound",
  "American Water Spaniel",
  "Anatolian Shepherd Dog",
  "Asong Pinoy",
  "Australian Cattle Dog",
  "Australian Kelpie",
  "Australian Shepherd",
  "Australian Terrier",
  "Azawakh",
  "Barbet (French Water Dog)",
  "Basenji",
  "Basset Artesien Normand (Artesian-Norman Basset)",
  "Basset Bleu De Gascogne (Blue Gascony Basset)",
  "Basset Fauve De Bretagne (Fawn Brittany Basset)",
  "Basset Hound",
  "Bavarian Mountain Scenthound",
  "Beagle",
  "Bearded Collie",
  "Beauceron",
  "Bedlington Terrier",
  "Belgian Laekenois",
  "Belgian Malinois",
  "Belgian Sheepdogbelgian Tervuren",
  "Berger Picardie (Berger Picard)",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Billy",
  "Black And Tan Coonhound",
  "Bloodhound",
  "Bolognese",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "Bracco Italiano (Italian Pointing Dogs)",
  "Briard",
  "Brittany Spaniel",
  "Bull Terrier",
  "Bulldog",
  "Bullmastiff",
  "Cairn Terrier",
  "Catalan Sheepdog",
  "Caucasian Shepherd Dog",
  "Cav King Charles Spaniel",
  "Central Asia Shepherd Dog",
  "Chart Polski (Polish Greyhound)",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chinese Crested Dog",
  "Chinese Shar-Pei",
  "Chow Chow",
  "Clumber Spaniel",
  "Collie (Rough)",
  "Coton De Tulear",
  "Curly Coated Retriever",
  "Czeslovakan Wolfdog",
  "Dachshund",
  "Dalmatian",
  "Dandie Dinmont Terrier",
  "Dederlandse Kooikerhondje",
  "Deerhound",
  "Deutsche Bracke (German Hound)",
  "Deutscher Wachtelhund (German Spaniel)",
  "Dobermann",
  "Dogo Argentino",
  "Dogo Canario",
  "Dogo De Bordeaux",
  "Drever (Swedish Dachsbracke)",
  "Dunker (Norwegian Hound)",
  "Dutch Shepherd",
  "English Cocker Spaniel",
  "English Foxhound",
  "English Pointer",
  "English Setter",
  "English Springer Spaniel",
  "Field Spaniel",
  "Fila Brasileiro",
  "Flat Coated Retriever",
  "Fox Terrier (Smooth)",
  "Fox Terrier (Wirehaired)",
  "French Bulldog",
  "Galgo Español (Spaniesh Greyhound)",
  "German Shepherd Dog",
  "German Shorthaired Pointer",
  "German Spitz",
  "German Wirehaired Pointer",
  "Giant Schnauzer",
  "Golden Retriever",
  "Gordon Setter",
  "Grand Basset Friffon Vendeen",
  "Grand Griffon Vendeen",
  "Great Dane",
  "Great Pyrenees",
  "Griffon (Brussels)",
  "Griffon",
  "Gronlandshund (Greenland Dog)",
  "Hamiltonstovare (Hamilton Hound)",
  "Hanoverian Scenthound",
  "Harrier",
  "Havanese",
  "Hrvatski Ovcar (Croatian Sheepdog)",
  "Irish Red & White Setter",
  "Irish Setter",
  "Irish Terrier",
  "Irish Water Spaniel",
  "Irish Wolfhound",
  "Italian Greyhound",
  "Italian Hound",
  "Jack Russell Terrier",
  "Japanese Chin",
  "Japanese Spitz",
  "Keeshond",
  "Kerry Blue Terrier",
  "Komondor",
  "Kuvasz",
  "Labrador Retriever",
  "Lagotto Romagnolo (Romagna Water Dog)",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Magyar Agar (Hungarian Greyhound)",
  "Maltese",
  "Manchester Terrier",
  "Mastiff",
  "Miniature Bull Terrier",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Neapolitan Mastiff",
  "Newfoundland",
  "Norwegian Elkhound",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Ogar Polski (Polish Hound)",
  "Old English Sheepdog",
  "Otterhound",
  "Papillon",
  "Parson Russell Terrier",
  "Pekingese",
  "Perro De Agua Español (Spanish Waterdog)",
  "Petit Basset Griffon Vendeen (Petit Basset Friffon Vendeen)",
  "Petit Chien Courant Suiwwe (Small Swiss Hound)",
  "Pointer",
  "Pomeranian",
  "Poodle",
  "Portuguese Water Dog",
  "Pug",
  "Puli",
  "Pumi",
  "Rhodesian Ridgeback",
  "Rottweiler",
  "Saluki",
  "Samoyed",
  "Schillerstovare (Schiller Hound)",
  "Schipperke",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Searloos Wolfdog",
  "Serbian Hound",
  "Serbian Tri Color Hound",
  "Shetland Sheepdog",
  "Shiba Inu",
  "Shih Tzu",
  "Siberian Husky",
  "Skye Terrier",
  "Sloughi (Arabian Greyhound)",
  "Slovensky Kopov (Slovakian Hound)",
  "Smalandestovare (Smaland Hound)",
  "Spanish Hound",
  "St Bernard",
  "Suomenajokoira (Finnish Hound)",
  "Sussex Spaniel",
  "Swiss Hound",
  "Tosa Inu",
  "Vizsla",
  "Weimaraner",
  "Welsch Corgi Pembroke",
  "Welsh Corgi Cardigan",
  "Welsh Springer Spaniel",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Westphalian Dachsbracke",
  "Wetterhound (Frisian Water Dog)",
  "Whippet",
  "Yorkshire Terrier"
]