import React from "react"
import CoatshineA from "./assets/media/1_3kg/coatshine.png"
import HiProteinA from "./assets/media/1_3kg/hi-protein.png"
import MaintenanceA from "./assets/media/1_3kg/maintenance.png"
import ObeefA from "./assets/media/1_3kg/o-beef.png"
import OlambA from "./assets/media/1_3kg/o-lamb.png"
import CoatshineB from "./assets/media/5kg/coatshine.png"
import HiProteinB from "./assets/media/5kg/hi-protein.png"
import MaintenanceB from "./assets/media/5kg/maintenance.png"
import ObeefB from "./assets/media/5kg/o-beef.png"
import OlambB from "./assets/media/5kg/o-lamb.png"
import CoatshineC from "./assets/media/10kg/coatshine.png"
import HiProteinC from "./assets/media/10kg/hi-protein.png"
import MaintenanceC from "./assets/media/10kg/maintenance.png"
import ObeefC from "./assets/media/10kg/o-beef.png"
import OlambC from "./assets/media/10kg/o-lamb.png"
import CoatshineD from "./assets/media/20kg/coatshine.png"
import HiProteinD from "./assets/media/20kg/hi-protein.png"
import MaintenanceD from "./assets/media/20kg/maintenance.png"
import ObeefD from "./assets/media/20kg/o-beef.png"
import OlambD from "./assets/media/20kg/o-lamb.png"
import WaterDispenserB from "./assets/media/premium/blue-water-dis.png"
import WaterDispenserR from "./assets/media/premium/red-water-dis.png"
import ProtekPlusL from "./assets/media/premium/protek-plus-l.png"
import ProtekPlusM from "./assets/media/premium/protek-plus-m.png"
import ProtekPlusS from "./assets/media/premium/protek-plus-s.jpg"
import SlowFeederB from "./assets/media/premium/slowfeeder-b.jpg"
import SlowFeederR from "./assets/media/premium/slowfeeder-r.jpg"

const productOrderList = [
    {
        id: 0,
        productImage: HiProteinA,
        productName: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor",
        productDescription: null,
        productPrice: 299,
        productType: "Dog food",
        productVariant: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor", 
        productWeight: "1.3kg",
        qty: 10,
    },
    {
        id: 1,
        productImage: HiProteinB,
        productName: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor",
        productDescription: null,
        productPrice: 899,
        productType: "Dog food", 
        productVariant: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor", 
        productWeight: "5kg", 
        qty: 10,
    },
    {
        id: 2,
        productImage: HiProteinC,
        productName: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor",
        productDescription: null,
        productPrice: 1550,
        productType: "Dog food", 
        productVariant: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor", 
        productWeight: "10kg", 
        qty: 10,
    },
    {
        id: 3,
        productImage: HiProteinD,
        productName: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor",
        productDescription: null,
        productPrice: 3100,
        productType: "Dog food", 
        productVariant: "Hi-Protein Puppy Lamb, Chicken Liver, and Milk Flavor", 
        productWeight: "20kg", 
        qty: 10,
    },
    {
        id: 4,
        productImage: CoatshineA,
        productName: "Coatshine Adult Salmon",
        productDescription: null,
        productPrice: 289,
        productType: "Dog food", 
        productVariant: "Coatshine Adult Salmon", 
        productWeight: "1.3kg", 
        qty: 10,
    },
    {
        id: 5,
        productImage: CoatshineB,
        productName: "Coatshine Adult Salmon",
        productDescription: null,
        productPrice: 899,
        productType: "Dog food", 
        productVariant: "Coatshine Adult Salmon", 
        productWeight: "5kg", 
        qty: 10,
    },
    {
        id: 6,
        productImage: CoatshineC,
        productName: "Coatshine Adult Salmon",
        productDescription: null,
        productPrice: 1550,
        productType: "Dog food", 
        productVariant: "Coatshine Adult Salmon", 
        productWeight: "10kg", 
        qty: 10,
    },
    {
        id: 7,
        productImage: CoatshineD,
        productName: "Coatshine Adult Salmon",
        productDescription: null,
        productPrice: 3100,
        productType: "Dog food", 
        productVariant: "Coatshine Adult Salmon", 
        productWeight: "20kg", 
        qty: 10,
    },
    {
        id: 8,
        productImage: OlambA,
        productName: "Optimum Adult Lamb",
        productDescription: null,
        productPrice: 279,
        productType: "Dog food", 
        productVariant: "Optimum Adult Lamb", 
        productWeight: "1.3kg", 
        qty: 10,
    },
    {
        id: 9,
        productImage: OlambB,
        productName: "Optimum Adult Lamb",
        productDescription: null,
        productPrice: 819,
        productType: "Dog food", 
        productVariant: "Optimum Adult Lamb", 
        productWeight: "5kg", 
        qty: 10,
    },
    {
        id: 10,
        productImage: OlambC,
        productName: "Optimum Adult Lamb",
        productDescription: null,
        productPrice: 1350,
        productType: "Dog food", 
        productVariant: "Optimum Adult Lamb", 
        productWeight: "10kg",
        qty: 10,
    },
    {
        id: 11,
        productImage: OlambD,
        productName: "Optimum Adult Lamb",
        productDescription: null,
        productPrice: 2700,
        productType: "Dog food", 
        productVariant: "Optimum Adult Lamb", 
        productWeight: "20kg",
        qty: 10,
    },
    {
        id: 12,
        productImage: ObeefA,
        productName: "Optimum Adult Beef + Chicken Liver",
        productDescription: null,
        productPrice: 259,
        productType: "Dog food", 
        productVariant: "Optimum Adult Beef + Chicken Liver", 
        productWeight: "1.3kg",
        qty: 10,
    },
    {
        id: 13,
        productImage: ObeefB,
        productName: "Optimum Adult Beef + Chicken Liver",
        productDescription: null,
        productPrice: 789,
        productType: "Dog food", 
        productVariant: "Optimum Adult Beef + Chicken Liver", 
        productWeight: "5kg",
        qty: 10,
    },
    {
        id: 14,
        productImage: ObeefC,
        productName: "Optimum Adult Beef + Chicken Liver",
        productDescription: null,
        productPrice: 1300,
        productType: "Dog food", 
        productVariant: "Optimum Adult Beef + Chicken Liver", 
        productWeight: "10kg",
        qty: 10,
    },
    {
        id: 15,
        productImage: ObeefD,
        productName: "Optimum Adult Beef + Chicken Liver",
        productDescription: null,
        productPrice: 2600,
        productType: "Dog food", 
        productVariant: "Optimum Adult Beef + Chicken Liver", 
        productWeight: "20kg",
        qty: 10,
    },
    {
        id: 16,
        productImage: MaintenanceA,
        productName: "Maintenance Adult Beef",
        productDescription: null,
        productPrice: 239,
        productType: "Dog food", 
        productVariant: "Maintenance Adult Beef", 
        productWeight: "1.3kg",
        qty: 10,
    },
    {
        id: 17,
        productImage: MaintenanceB,
        productName: "Maintenance Adult Beef",
        productDescription: null,
        productPrice: 699,
        productType: "Dog food", 
        productVariant: "Maintenance Adult Beef", 
        productWeight: "5kg",
        qty: 10,
    },
    {
        id: 18,
        productImage: MaintenanceC,
        productName: "Maintenance Adult Beef",
        productDescription: null,
        productPrice: 1150,
        productType: "Dog food", 
        productVariant: "Maintenance Adult Beef", 
        productWeight: "10kg",
        qty: 10,
    },
    {
        id: 19,
        productImage: MaintenanceD,
        productName: "Maintenance Adult Beef",
        productDescription: null,
        productPrice: 2300,
        productType: "Dog food", 
        productVariant: "Maintenance Adult Beef", 
        productWeight: "20kg",
        qty: 10,
    },
    {
        id: 20,
        productImage: ProtekPlusS,
        productName: "Protect Plus",
        productDescription: null,
        productPrice: 70,
        productType: "disinfectants", 
        productVariant: null, 
        productWeight: "100ml",
        qty: 10,
    },
    {
        id: 21,
        productImage: ProtekPlusM,
        productName: "Protect Plus",
        productDescription: null,
        productPrice: 75,
        productType: "disinfectants", 
        productVariant: null, 
        productWeight: "Gold 20g",
        qty: 10,
    },
    {
        id: 22,
        productImage: ProtekPlusL,
        productName: "Protect Plus",
        productDescription: null,
        productPrice: 1615,
        productType: "disinfectants", 
        productVariant: null, 
        productWeight: "Gold 1kg",
        qty: 10,
    },
    {
        id: 23,
        productImage: SlowFeederR,
        productName: "Nutri Chunks Slow Feeding Dog Dish",
        productDescription: null,
        productPrice: 249,
        productType: "Premium", 
        productVariant: "red", 
        productWeight: null,
        qty: 10,
    },
    {
        id: 24,
        productImage: SlowFeederB,
        productName: "Nutri Chunks Slow Feeding Dog Dish",
        productDescription: null,
        productPrice: 249,
        productType: "Premium", 
        productVariant: "blue", 
        productWeight: null,
        qty: 10,
    },
    {
        id: 25,
        productImage: WaterDispenserB,
        productName: "Nutri Chunks Automatic Water Dispensing Dish",
        productDescription: null,
        productPrice: 149,
        productType: "Premium", 
        productVariant: "blue", 
        productWeight: null,
        qty: 10,
    },
    {
        id: 26,
        productImage: WaterDispenserR,
        productName: "Nutri Chunks Automatic Water Dispensing Dish",
        productDescription: null,
        productPrice: 149,
        productType: "Premium", 
        productVariant: "red", 
        productWeight: null,
        qty: 10,
    },
]

export default productOrderList;